### ISSUE TITLE
CMIP6 interface mixes Amon and Omon

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#41]
Developing xarray version of the `global_mean.py` I found out that the current filenames expansion i.e. `_expand_filename()` does not make any difference between `Amon` and `Omon` variables, so that if both are available both are loaded and averaged together. This occurs specifically for historical EC-Earth3 on mafalda when computing `net_sfc`, which requires snow (`prsn`) which is available for both Amon and Omon, but other potential situation like this are possible.
CDO does not complaint since it just do global average, but xarray crashes so that I spotted the issue. 

This has to be solved in the main branch: a possible workaround currently used in the xarray branch is to prepend an *A* and *O* to the filename definition in the `interface_CMIP6.yml` as done here below:

```
filetype:
  atm2d:
    filename: '{var}_A{frequency}_{model}_{expname}_{ensemble}_{grid}_{year1}01-{year2}12.nc'
    dir: '{ensemble}/{frequency}/{var}/{grid}/{version}'
    component: cmoratm
  atm3d:
    filename: '{var}_A{frequency}_{model}_{expname}_{ensemble}_{grid}_{year1}01-{year2}12.nc'
    dir: '{ensemble}/{frequency}/{var}/{grid}/{version}'
    component: cmoratm
  oce2d:
    filename: '{var}_O{frequency}_{model}_{expname}_{ensemble}_{grid}_{year1}01-{year2}12.nc'
    dir: '{ensemble}/{frequency}/{var}/{grid}/{version}'
    component: cmoroce
  ice:
    filename: '{var}_{frequency}_{model}_{expname}_{ensemble}_{grid}_{year1}01-{year2}12.nc'
    dir: '{ensemble}/{frequency}/{var}/{grid}/{version}'
    component: cmoroce
```

It is not clean but solves all the issues so far.
