### ISSUE TITLE
Non-cmor variables

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#63]
Interface files are very convenient but apparently we forgot to consider the hypothesis when a variable is not saved under a cmor name. As an example we consider `2t` as output from raw IFS data or ERA5 reanalysis. We cannot change the variable name in the `config.yml` since this will break any comparison.

 We should introduce a the possibility  that the interface file have a specification of which variable to be loaded/seeked, that might be different from the cmor name. Something as 

```
 tas:
    varload: '2t'
    varnname: '2m Temperature'
    filetype: atm2d 
```

The new `varload` should be present everywhere in the code, and set as identical to `var` in the case this is not defined. This should also come with a revisitation of the `make_input_filename()` function which does not allow for such flexibility

**Comment by oloapinivad** [comment]
This can be a source of confusion for `derived` variables, and must be treated with caution. If we do not use cmor names in the derivation, we might face some complication when looking for variables within the file. Conversely, it is clumsy to creation expression based on cmor variables.

**Comment by oloapinivad** [comment]
I have just realized that this can be easily done using the `derived` keys. 

```
 tas:
    derived: '2t'
    varnname: '2m Temperature'
    filetype: atm2d 
```

Some rearrangement of the file loading is currently being developed in #59, but this can be easily exploited!
