### ISSUE TITLE
Revisiting the `component` and its files in the interface YAML files

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#65]
ECmean4 is built on the present of a series of components which tells the inner code how to deal with land-sea masks, grid areas and grid specifications. These are listed within the `component` block of the interface files

As an exemple, for cmor they reads as:

```
component:
  cmoratm:
    inifile: 'r1i1p1f*/sftlf/sftlf_fx_{model}_{expname}_r1i1p1f*_{grid}.nc'
    atmfile: 'r1i1p1f*/sftlf/sftlf_fx_{model}_{expname}_r1i1p1f*_{grid}.nc'
  cmoroce:
    gridfile: 'r1i1p1f*/sftof/sftof_Ofx_{model}_{expname}_r1i1p1f*_{grid}.nc'
    areafile: 'r1i1p1f*/areacello/areacello_Ofx_{model}_{expname}_r1i1p1f*_{grid}.nc'
```

As another example, EC-Earth4 reads: 

```
component:
  oifs:
    inifile: 'ICMGG{expname}INIT'
    atmfile: 'output/oifs/{expname}_atm_cmip6_1m_{year1}-{year2}.nc'
  nemo:
    gridfile: nemo-initial-state.nc
    areafile: domain_cfg.nc
```

The naming is non consistent, and also the goal of each this file can be not trivial to understand. In principle what we mandatory need is:

1. Land-sea mask file on the atmospheric grid (mandatory)
2. Land-sea mask file on the oceanic grid (not mandatory, see #38)
3. Area file for atmospheric grid (it could be whatever file in most cases, since `_area_cell()` has been shown to cover many cases)
4. Area file oceanic grid (the standard `areacello` in CMOR)
5. Area file ice grid (some cmor model has this peculiarity, see #47)

What is the need of the oceanic `gridfile` in this configuration needs to be assessed: this was originally introduced for EC-Earth4 but maybe can be included in the `areafile`. 

Furthermore, each `component` implies different treating by the mask and interpolation functions, and this is very much ad hoc.

A general reorganization must be carried out to support different models.

**Comment by oloapinivad** [comment]
This commit https://github.com/oloapinivad/ECmean4/pull/59/commits/07242c3024c253ba7314e5ef3155f08018de4806b we solve the most of the issues introducing a 3-file interface file, with uniform naming.

The idea is that each component has a `maskfile`, a `gridfile` and an `areafile`.  The former is mandatory only for the atmosphere, since no ocean mask file is used in oceanic computation for the moment. 
For interpolation and area computation, the code look initially for `areafile`, and if not available, for the `gridfile` and then `maskfile`.  In this way there are multiple combination possible to create flexible interface file.

```
component:
  oifs:
    maskfile: 'ICMGG{expname}INIT'
    gridfile: 'output/oifs/{expname}_atm_cmip6_1m_{year1}-{year2}.nc'
    areafile: ''
  nemo:
    maskfile: ''
    gridfile: ''
    areafile: 'nemo-initial-state.nc'
```

We also realized that the interface file for EC-Earth4 could be simplified.
